"""feat: add autogenerate to request timestamp

Revision ID: 120b1660d51c
Revises: ec9ee3f4be13
Create Date: 2023-03-27 20:56:14.579092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120b1660d51c'
down_revision = 'ec9ee3f4be13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
