"""First Commit

Revision ID: 64da2ee7d260
Revises: 
Create Date: 2023-03-26 16:31:43.782907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64da2ee7d260'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('start_time_local', sa.TIME(), nullable=True),
    sa.Column('start_time_end', sa.TIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_hours_id'), 'store_hours', ['id'], unique=False)
    op.create_table('store_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('timestamp_utc', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_status_id'), 'store_status', ['id'], unique=False)
    op.create_table('store_timezones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(), nullable=True),
    sa.Column('timezone_str', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_timezones_id'), 'store_timezones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_timezones_id'), table_name='store_timezones')
    op.drop_table('store_timezones')
    op.drop_index(op.f('ix_store_status_id'), table_name='store_status')
    op.drop_table('store_status')
    op.drop_index(op.f('ix_store_hours_id'), table_name='store_hours')
    op.drop_table('store_hours')
    # ### end Alembic commands ###
