"""feat: add reports table

Revision ID: ec9ee3f4be13
Revises: cb8bd3fe2c2d
Create Date: 2023-03-26 19:21:39.419102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9ee3f4be13'
down_revision = 'cb8bd3fe2c2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('report_status', sa.String(), nullable=True),
    sa.Column('report', sa.String(), nullable=True),
    sa.Column('request_timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('generation_timestamp', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_reports_report_id'), 'reports', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_report_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
